# Generated by Django 4.1 on 2024-04-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='likes',
            new_name='like',
        ),
    ]
