# Generated by Django 4.1 on 2024-06-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='member',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
