# Generated by Django 4.2.7 on 2024-01-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
