# Generated by Django 4.1 on 2024-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
