# Generated by Django 4.2.7 on 2024-01-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_follow'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
