# Generated by Django 4.2.7 on 2024-01-08 03:41

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_managers_follow_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='follow',
            managers=[
                ('objects', base.managers.Mymanager()),
            ],
        ),
    ]
