# Generated by Django 3.2.7 on 2024-01-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_follow_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='follow',
            managers=[
            ],
        ),
    ]
