# Generated by Django 3.2.7 on 2024-02-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_follow_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
