# Generated by Django 4.1 on 2024-04-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_room_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
