# Generated by Django 3.2.7 on 2024-04-02 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_liking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liking',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liking',
            name='unlike',
            field=models.ManyToManyField(blank=True, related_name='user_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
