# Generated by Django 4.1 on 2024-04-08 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='follower',
            field=models.ManyToManyField(null=True, related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='following',
            field=models.ManyToManyField(null=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='like',
            field=models.ManyToManyField(null=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
