# Generated by Django 4.1 on 2024-04-08 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_room_follower_room_following_room_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
