# Generated by Django 3.2.7 on 2024-04-02 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20240402_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='liking',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
