# Generated by Django 4.1 on 2024-04-08 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_liking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liking',
            name='like',
        ),
        migrations.RemoveField(
            model_name='liking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='liking',
            name='unlike',
        ),
        migrations.RemoveField(
            model_name='liking',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Liking',
        ),
    ]
