# Generated by Django 3.2.7 on 2024-04-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='room',
            name='following',
        ),
    ]
