# Generated by Django 3.2.7 on 2024-04-18 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20240418_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ManyToManyField(related_name='the_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
