# Generated by Django 3.2.7 on 2024-04-18 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_follow_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
