# Generated by Django 4.1 on 2024-04-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20240418_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', '-created']},
        ),
    ]
