# Generated by Django 4.1 on 2024-04-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', 'updated']},
        ),
    ]
